


#OUTPUT_PATH = ../output

#VIVADO_OPTS = -journal


all:
	vivado -mode batch -source full_build.tcl -nojournal -nolog -tempDir ./work

prog:
	vivado -mode batch -source program_fpga.tcl -nojournal -nolog  -tempDir ./work


clean:
	echo "cats"