
#Switches
#set_property -dict { PACKAGE_PIN G15   IOSTANDARD LVCMOS33 } [get_ports { btns_4bits_tri_i[0] }]; #IO_L19N_T3_VREF_35 Sch=SW0
#set_property -dict { PACKAGE_PIN P15   IOSTANDARD LVCMOS33 } [get_ports { btns_4bits_tri_i[1] }];  #IO_L24P_T3_34 Sch=SW1
#set_property -dict { PACKAGE_PIN W13   IOSTANDARD LVCMOS33 } [get_ports { btns_4bits_tri_i[2] }]; #IO_L4N_T0_34 Sch=SW2
#set_property -dict { PACKAGE_PIN T16   IOSTANDARD LVCMOS33 } [get_ports { btns_4bits_tri_i[3] }]; #IO_L9P_T1_DQS_34 Sch=SW3


#LEDs
set_property PACKAGE_PIN M14 [get_ports {leds_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[0]}]
set_property PACKAGE_PIN M15 [get_ports {leds_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[1]}]
set_property PACKAGE_PIN G14 [get_ports {leds_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[2]}]
set_property PACKAGE_PIN D18 [get_ports {leds_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[3]}]

set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports neopixel_drive]

set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports clock_125m]
create_clock -period 8.000 [get_ports clock_125m]

connect_debug_port u_ila_0/clk [get_nets [list clock_125m_IBUF_BUFG]]
connect_debug_port u_ila_0/probe0 [get_nets [list {neopixel_i/blue_value_reg[3]_3[0]} {neopixel_i/blue_value_reg[3]_3[1]} {neopixel_i/blue_value_reg[3]_3[2]} {neopixel_i/blue_value_reg[3]_3[3]} {neopixel_i/blue_value_reg[3]_3[4]} {neopixel_i/blue_value_reg[3]_3[5]} {neopixel_i/blue_value_reg[3]_3[6]} {neopixel_i/blue_value_reg[3]_3[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {neopixel_driver_i/pixel_address[0]} {neopixel_driver_i/pixel_address[1]} {neopixel_driver_i/pixel_address[2]} {neopixel_driver_i/pixel_address[3]} {neopixel_driver_i/pixel_address[4]} {neopixel_driver_i/pixel_address[5]} {neopixel_driver_i/pixel_address[6]} {neopixel_driver_i/pixel_address[7]} {neopixel_driver_i/pixel_address[8]} {neopixel_driver_i/pixel_address[9]} {neopixel_driver_i/pixel_address[10]} {neopixel_driver_i/pixel_address[11]} {neopixel_driver_i/pixel_address[12]} {neopixel_driver_i/pixel_address[13]} {neopixel_driver_i/pixel_address[14]} {neopixel_driver_i/pixel_address[15]} {neopixel_driver_i/pixel_address[16]} {neopixel_driver_i/pixel_address[17]} {neopixel_driver_i/pixel_address[18]} {neopixel_driver_i/pixel_address[19]} {neopixel_driver_i/pixel_address[20]} {neopixel_driver_i/pixel_address[21]} {neopixel_driver_i/pixel_address[22]} {neopixel_driver_i/pixel_address[23]} {neopixel_driver_i/pixel_address[24]} {neopixel_driver_i/pixel_address[25]} {neopixel_driver_i/pixel_address[26]} {neopixel_driver_i/pixel_address[27]} {neopixel_driver_i/pixel_address[28]} {neopixel_driver_i/pixel_address[29]} {neopixel_driver_i/pixel_address[30]} {neopixel_driver_i/pixel_address[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {neopixel_i/blue_value_reg[5]_5[0]} {neopixel_i/blue_value_reg[5]_5[1]} {neopixel_i/blue_value_reg[5]_5[2]} {neopixel_i/blue_value_reg[5]_5[3]} {neopixel_i/blue_value_reg[5]_5[4]} {neopixel_i/blue_value_reg[5]_5[5]} {neopixel_i/blue_value_reg[5]_5[6]} {neopixel_i/blue_value_reg[5]_5[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {neopixel_i/blue_value_reg[9]_9[0]} {neopixel_i/blue_value_reg[9]_9[1]} {neopixel_i/blue_value_reg[9]_9[2]} {neopixel_i/blue_value_reg[9]_9[3]} {neopixel_i/blue_value_reg[9]_9[4]} {neopixel_i/blue_value_reg[9]_9[5]} {neopixel_i/blue_value_reg[9]_9[6]} {neopixel_i/blue_value_reg[9]_9[7]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {neopixel_i/blue_value_reg[7]_7[0]} {neopixel_i/blue_value_reg[7]_7[1]} {neopixel_i/blue_value_reg[7]_7[2]} {neopixel_i/blue_value_reg[7]_7[3]} {neopixel_i/blue_value_reg[7]_7[4]} {neopixel_i/blue_value_reg[7]_7[5]} {neopixel_i/blue_value_reg[7]_7[6]} {neopixel_i/blue_value_reg[7]_7[7]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {neopixel_i/blue_value_reg[1]_1[0]} {neopixel_i/blue_value_reg[1]_1[1]} {neopixel_i/blue_value_reg[1]_1[2]} {neopixel_i/blue_value_reg[1]_1[3]} {neopixel_i/blue_value_reg[1]_1[4]} {neopixel_i/blue_value_reg[1]_1[5]} {neopixel_i/blue_value_reg[1]_1[6]} {neopixel_i/blue_value_reg[1]_1[7]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {neopixel_i/blue_value_reg[2]_2[0]} {neopixel_i/blue_value_reg[2]_2[1]} {neopixel_i/blue_value_reg[2]_2[2]} {neopixel_i/blue_value_reg[2]_2[3]} {neopixel_i/blue_value_reg[2]_2[4]} {neopixel_i/blue_value_reg[2]_2[5]} {neopixel_i/blue_value_reg[2]_2[6]} {neopixel_i/blue_value_reg[2]_2[7]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {neopixel_i/blue_value_reg[8]_8[0]} {neopixel_i/blue_value_reg[8]_8[1]} {neopixel_i/blue_value_reg[8]_8[2]} {neopixel_i/blue_value_reg[8]_8[3]} {neopixel_i/blue_value_reg[8]_8[4]} {neopixel_i/blue_value_reg[8]_8[5]} {neopixel_i/blue_value_reg[8]_8[6]} {neopixel_i/blue_value_reg[8]_8[7]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {neopixel_i/blue_value_reg[6]_6[0]} {neopixel_i/blue_value_reg[6]_6[1]} {neopixel_i/blue_value_reg[6]_6[2]} {neopixel_i/blue_value_reg[6]_6[3]} {neopixel_i/blue_value_reg[6]_6[4]} {neopixel_i/blue_value_reg[6]_6[5]} {neopixel_i/blue_value_reg[6]_6[6]} {neopixel_i/blue_value_reg[6]_6[7]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {neopixel_i/blue_value_reg[0]_0[0]} {neopixel_i/blue_value_reg[0]_0[1]} {neopixel_i/blue_value_reg[0]_0[2]} {neopixel_i/blue_value_reg[0]_0[3]} {neopixel_i/blue_value_reg[0]_0[4]} {neopixel_i/blue_value_reg[0]_0[5]} {neopixel_i/blue_value_reg[0]_0[6]} {neopixel_i/blue_value_reg[0]_0[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {neopixel_i/blue_value_reg[4]_4[0]} {neopixel_i/blue_value_reg[4]_4[1]} {neopixel_i/blue_value_reg[4]_4[2]} {neopixel_i/blue_value_reg[4]_4[3]} {neopixel_i/blue_value_reg[4]_4[4]} {neopixel_i/blue_value_reg[4]_4[5]} {neopixel_i/blue_value_reg[4]_4[6]} {neopixel_i/blue_value_reg[4]_4[7]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {pixel_write_data[0]} {pixel_write_data[1]} {pixel_write_data[2]} {pixel_write_data[3]} {pixel_write_data[4]} {pixel_write_data[5]} {pixel_write_data[6]} {pixel_write_data[7]} {pixel_write_data[8]} {pixel_write_data[9]} {pixel_write_data[10]} {pixel_write_data[11]} {pixel_write_data[12]} {pixel_write_data[13]} {pixel_write_data[14]} {pixel_write_data[15]} {pixel_write_data[16]} {pixel_write_data[17]} {pixel_write_data[18]} {pixel_write_data[19]} {pixel_write_data[20]} {pixel_write_data[21]} {pixel_write_data[22]} {pixel_write_data[23]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {neopixel_i/blue_value_reg[10]_10[0]} {neopixel_i/blue_value_reg[10]_10[1]} {neopixel_i/blue_value_reg[10]_10[2]} {neopixel_i/blue_value_reg[10]_10[3]} {neopixel_i/blue_value_reg[10]_10[4]} {neopixel_i/blue_value_reg[10]_10[5]} {neopixel_i/blue_value_reg[10]_10[6]} {neopixel_i/blue_value_reg[10]_10[7]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {neopixel_i/blue_value_reg[11]_11[0]} {neopixel_i/blue_value_reg[11]_11[1]} {neopixel_i/blue_value_reg[11]_11[2]} {neopixel_i/blue_value_reg[11]_11[3]} {neopixel_i/blue_value_reg[11]_11[4]} {neopixel_i/blue_value_reg[11]_11[5]} {neopixel_i/blue_value_reg[11]_11[6]} {neopixel_i/blue_value_reg[11]_11[7]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list neopixel_driver_i/pixel_wren]]
connect_debug_port dbg_hub/clk [get_nets clock_125m_IBUF_BUFG]

create_debug_core u_ila_0_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0_0]
set_property port_width 1 [get_debug_ports u_ila_0_0/clk]
connect_debug_port u_ila_0_0/clk [get_nets [list top_hw_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe0]
connect_debug_port u_ila_0_0/probe0 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[8]_8[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[8]_8[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[8]_8[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[8]_8[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[8]_8[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[8]_8[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[8]_8[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[8]_8[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe1]
connect_debug_port u_ila_0_0/probe1 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[10]_10[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[10]_10[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[10]_10[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[10]_10[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[10]_10[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[10]_10[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[10]_10[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[10]_10[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe2]
connect_debug_port u_ila_0_0/probe2 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[1]_1[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[1]_1[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[1]_1[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[1]_1[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[1]_1[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[1]_1[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[1]_1[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[1]_1[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe3]
connect_debug_port u_ila_0_0/probe3 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[11]_11[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[11]_11[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[11]_11[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[11]_11[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[11]_11[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[11]_11[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[11]_11[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[11]_11[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe4]
connect_debug_port u_ila_0_0/probe4 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[0]_0[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[0]_0[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[0]_0[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[0]_0[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[0]_0[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[0]_0[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[0]_0[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[0]_0[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe5]
connect_debug_port u_ila_0_0/probe5 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[6]_6[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[6]_6[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[6]_6[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[6]_6[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[6]_6[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[6]_6[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[6]_6[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[6]_6[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe6]
connect_debug_port u_ila_0_0/probe6 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[2]_2[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[2]_2[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[2]_2[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[2]_2[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[2]_2[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[2]_2[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[2]_2[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[2]_2[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe7]
connect_debug_port u_ila_0_0/probe7 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[3]_3[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[3]_3[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[3]_3[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[3]_3[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[3]_3[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[3]_3[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[3]_3[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[3]_3[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe8]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe8]
connect_debug_port u_ila_0_0/probe8 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[7]_7[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[7]_7[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[7]_7[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[7]_7[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[7]_7[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[7]_7[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[7]_7[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[7]_7[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe9]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe9]
connect_debug_port u_ila_0_0/probe9 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[4]_4[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[4]_4[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[4]_4[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[4]_4[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[4]_4[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[4]_4[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[4]_4[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[4]_4[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe10]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe10]
connect_debug_port u_ila_0_0/probe10 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[9]_9[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[9]_9[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[9]_9[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[9]_9[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[9]_9[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[9]_9[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[9]_9[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[9]_9[7]}]]
create_debug_port u_ila_0_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0_0/probe11]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe11]
connect_debug_port u_ila_0_0/probe11 [get_nets [list {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[5]_5[0]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[5]_5[1]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[5]_5[2]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[5]_5[3]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[5]_5[4]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[5]_5[5]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[5]_5[6]} {top_hw_i/myNeoPixelDriver_0/inst/myNeoPixelDriver_v1_0_S00_AXI_inst/neopixel_i/blue_value_reg[5]_5[7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_0_FCLK_CLK0]
